<?php

namespace AppBundle\Repository;

/**
 * OrderCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCardRepository extends \Doctrine\ORM\EntityRepository
{
}
