<?php

namespace AppBundle\Repository;

/**
 * OrderFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderFileRepository extends \Doctrine\ORM\EntityRepository
{
}
