<?php

namespace AppBundle\Repository;

/**
 * OrderCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
